version: "3.8"
services:
  movies:
    image: techmahi821/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: techmahi821/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: techmahi821/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: techmahi821/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
